server:
  port: 8091
  servlet:
    context-path: /harmony
spring:
  application:
    name: ui-service
  datasource:
    url: jdbc:mysql://localhost:3306/plneng
    username: plneng
    password: plneng
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
jsf:
  primefaces:
    theme: harmony-absolution
